#!/usr/bin/env npx tsx
/**
 * Generate CLI reference documentation from command registry
 * Output: engine/memory/context/cli-tools-reference.md
 */

// Register all commands
import './commands/competitors/list.js';
import './commands/competitors/add.js';
import './commands/competitors/sync.js';
import './commands/competitors/analyze.js';
import './commands/competitors/top-notes.js';
import './commands/competitors/summarize.js';
import './commands/materials/list.js';
import './commands/materials/create.js';
import './commands/materials/import-url.js';
import './commands/materials/search-trending.js';
import './commands/ai/generate.js';
import './commands/ai/publish.js';
import './commands/ai/check-script.js';
import './commands/ai/optimize-script.js';
import './commands/ai/match-framework.js';
import './commands/scripts/list.js';
import './commands/scripts/create.js';
import './commands/scripts/breakdown.js';
import './commands/publish/list.js';
import './commands/publish/create.js';
import './commands/publish/auto-draft.js';

import { listModules, listCommands } from './registry.js';
import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';

async function main() {
  const lines: string[] = [
    '# CLI Tools Reference',
    '',
    '> Auto-generated by `npx tsx engine/cli/gen-docs.ts`',
    '',
    '## 使用方式',
    '```bash',
    'npx tsx engine/cli/run.ts <module> <action> [--param value ...]',
    'npx tsx engine/cli/run.ts --help              # 查看所有模块',
    'npx tsx engine/cli/run.ts <module> --help      # 查看模块内命令',
    '```',
    '',
    '## 输出格式',
    '所有命令输出 JSON:',
    '```json',
    '{ "success": true, "data": { ... }, "meta": { "endpoint": "...", "method": "...", "duration_ms": 123 } }',
    '```',
    '',
  ];

  for (const mod of listModules()) {
    lines.push(`## ${mod}`);
    lines.push('');

    for (const cmd of listCommands(mod)) {
      lines.push(`### \`${cmd.module} ${cmd.action}\`${cmd.actionAlias ? ` (\`${cmd.actionAlias}\`)` : ''}`);
      lines.push('');
      lines.push(cmd.description);
      lines.push('');
      lines.push(`- **Endpoint**: \`${cmd.method} ${cmd.endpoint}\``);

      if (cmd.params.length > 0) {
        lines.push('- **参数**:');
        for (const p of cmd.params) {
          const req = p.required ? '必填' : `可选${p.default !== undefined ? `, 默认: ${p.default}` : ''}`;
          lines.push(`  - \`--${p.name}\`${p.alias ? ` / \`--${p.alias}\`` : ''} — ${p.description} (${req})`);
        }
      }

      lines.push('');
      // Usage example
      const exampleArgs = cmd.params.map((p) => `--${p.name} ${p.type === 'string' ? '"..."' : p.type === 'number' ? '123' : 'true'}`).join(' ');
      lines.push(`\`\`\`bash`);
      lines.push(`npx tsx engine/cli/run.ts ${cmd.module} ${cmd.action} ${exampleArgs}`.trim());
      lines.push(`\`\`\``);
      lines.push('');
    }
  }

  const outDir = join(import.meta.dirname, '..', 'memory', 'context');
  await mkdir(outDir, { recursive: true });
  const outPath = join(outDir, 'cli-tools-reference.md');
  await writeFile(outPath, lines.join('\n'), 'utf-8');
  console.log(`Generated: ${outPath}`);
}

main().catch(console.error);
